# Place this file into config folder of your RailsRoot
api-key: '16aa9a47-84ad-437b-aa06-9658bd7c8341'
development:
 enabled: true
production:
  enabled: true
staging:
  api-key: '16aa9a47-84ad-437b-aa06-9658bd7c8341' # You can change if you have create different project
  enabled: true
